FROM node:12-alpine As development

WORKDIR /usr/src/app
COPY ./package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:12-alpine

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
WORKDIR /usr/src/app
COPY ./package*.json ./
RUN npm install --only=production
COPY --from=development /usr/src/app/dist/api .
EXPOSE 8080

CMD ["node", "main"]
